/** 07_Rekap.gs - rekap cepat: absensi + poin diagregasi sekali per periode. */
function buildRekap_(period,params){
  params=params||{};if(!['mingguan','bulanan','semester','tahunan'].includes(String(period)))throw new Error('Periode laporan tidak valid.');
  const kelas=params.kelas==null?'':String(params.kelas).trim(),rows=getRekapAbsensi_(period,params.year,params.month,params.semester,kelas,params.weekStart),b=getPeriodBounds_(period,params),start=b.start,end=b.end;
  const agg=aggregatePointPeriod_(start,end),master=getSiswa_(),order={};master.forEach((x,i)=>order[String(x.nisn).trim()]=i);
  const result=rows.map(s=>{const a=agg[String(s.nisn).trim()]||{pel:0,rew:0,count:0},bersih=Math.max(0,a.pel-a.rew);return Object.assign({},s,{jmlPelanggaran:a.count,poinPelanggaran:toNumberPoin_(a.pel),poinPenghargaan:toNumberPoin_(a.rew),poinBersih:toNumberPoin_(bersih),statusPembinaan:getKeputusanPoin_(bersih).status});});
  result.sort((a,b)=>{const ia=order[String(a.nisn).trim()],ib=order[String(b.nisn).trim()];if(ia!==undefined&&ib!==undefined)return ia-ib;if(ia!==undefined)return-1;if(ib!==undefined)return 1;return String(a.nama||'').localeCompare(String(b.nama||''),'id',{sensitivity:'base'});});return result;
}
function aggregatePointPeriod_(start,end){
  const key=cacheKey_('POINT_PERIOD',[cacheDateKey_(start),cacheDateKey_(end)]);
  const cached=cacheGetJson_(key);if(cached)return cached;
  const out={};
  const pel=dbRead_(APP.SHEETS.PELANGGARAN),rew=dbRead_(APP.SHEETS.PENGHARGAAN),range=dateRangeInclusive_(formatInputDate_(start),formatInputDate_(end));
  function add(d,type){const cn=dbFindColumn_(d.map,['NISN','NIS','Nomor Induk Siswa Nasional']),cd=dbFindColumn_(d.map,['Tanggal','Tanggal Pelanggaran','Tanggal Penghargaan','Tgl']),cp=dbFindColumn_(d.map,['Poin','Point']);if(cn<0||cd<0||cp<0)return;d.rows.forEach(r=>{const nisn=String(r[cn]??'').trim(),dt=dbDate_(r[cd]);if(!nisn||!dt||dt<range.a||dt>range.b)return;if(!out[nisn])out[nisn]={pel:0,rew:0,count:0};const p=toNumberPoin_(r[cp]);if(type==='pel'){out[nisn].pel+=p;out[nisn].count++;}else out[nisn].rew+=p;});}
  add(pel,'pel');add(rew,'rew');return cachePutJson_(key,out,CACHE_TTL.DERIVED);
}
function getPointSummaryMap_(start,end,tahunPelajaran){
  const key=cacheKey_('POINT_SUMMARY',[cacheDateKey_(start),cacheDateKey_(end),tahunPelajaran||'ALL']);
  const cached=cacheGetJson_(key);if(cached)return cached;
  const out={};
  const range=dateRangeInclusive_(start,end);
  const add=(sheetName,type)=>{
    const d=dbRead_(sheetName);
    const cn=dbFindColumn_(d.map,['NISN','NIS','Nomor Induk Siswa Nasional']);
    const cd=dbFindColumn_(d.map,['Tanggal','Tanggal Pelanggaran','Tanggal Penghargaan','Tgl']);
    const cp=dbFindColumn_(d.map,['Poin','Point']);
    const ctp=dbFindColumn_(d.map,['Tahun_Pelajaran','Tahun Pelajaran','TP']);
    if(cn<0||cp<0)return;
    d.rows.forEach(r=>{
      const nisn=String(r[cn]??'').trim();
      if(!nisn)return;
      if(tahunPelajaran && ctp>=0 && String(r[ctp]??'').trim()!==String(tahunPelajaran).trim())return;
      const dt=cd>=0?dbDate_(r[cd]):null;
      if(range.a&&(!dt||dt<range.a))return;
      if(range.b&&(!dt||dt>range.b))return;
      if(!out[nisn])out[nisn]={pel:0,rew:0};
      const poin=toNumberPoin_(r[cp]);
      if(type==='pel')out[nisn].pel+=poin;else out[nisn].rew+=poin;
    });
  };
  add(APP.SHEETS.PELANGGARAN,'pel');
  add(APP.SHEETS.PENGHARGAAN,'rew');
  return cachePutJson_(key,out,CACHE_TTL.DERIVED);
}
function getPeriodBounds_(period,p){p=p||{};const y=Number(p.year||new Date().getFullYear());if(period==='mingguan'){const start=parseDateInput_(p.weekStart||new Date());start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+6);end.setHours(23,59,59,999);return{start:start,end:end};}if(period==='bulanan'){const m=Number(p.month||1);return{start:new Date(y,m-1,1,0,0,0),end:new Date(y,m,0,23,59,59,999)};}if(period==='semester')return String(p.semester)==='2'?{start:new Date(y+1,0,1),end:new Date(y+1,5,30,23,59,59,999)}:{start:new Date(y,6,1),end:new Date(y,11,31,23,59,59,999)};return{start:new Date(y,6,1),end:new Date(y+1,5,30,23,59,59,999)};}
function getPeriodLabel_(period,p){p=p||{};const y=Number(p.year||new Date().getFullYear()),months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];if(period==='mingguan'){const b=getPeriodBounds_(period,p);return'Minggu '+formatTanggal_(b.start)+' s.d. '+formatTanggal_(b.end);}if(period==='bulanan')return'Bulan '+(months[Number(p.month||1)-1]||'')+' '+y;if(period==='semester')return'Semester '+String(p.semester||1)+' — Tahun Pelajaran '+(p.tahunPelajaran||getTahunPelajaran_());return'Tahun Pelajaran '+(p.tahunPelajaran||getTahunPelajaran_());}
function getReportStatistics_(data){data=data||[];const n=data.length;return{jumlahSiswa:n,rataKehadiran:n?+(data.reduce((a,x)=>a+Number(x.kehadiran||0),0)/n).toFixed(2):0,totalPelanggaran:data.reduce((a,x)=>a+Number(x.poinPelanggaran||0),0),totalPenghargaan:data.reduce((a,x)=>a+Number(x.poinPenghargaan||0),0),perluPembinaan:data.filter(x=>x.statusPembinaan&&x.statusPembinaan!=='NORMAL').length};}
function getStudentReportDetail_(nisn,period,params){params=params||{};const b=getPeriodBounds_(period,params),s=findStudentByNisn_(nisn);if(!s)throw new Error('Siswa tidak ditemukan.');const abs=getRekapAbsensi_(period,params.year,params.month,params.semester,params.kelas||'').filter(x=>String(x.nisn)===String(nisn))[0]||Object.assign({},s,{H:0,S:0,I:0,A:0,T:0,D:0,kehadiran:0}),pel=getPelanggaranSiswa_(nisn,formatInputDate_(b.start),formatInputDate_(b.end)),rew=getPenghargaanSiswa_(nisn,formatInputDate_(b.start),formatInputDate_(b.end)),pp=pel.reduce((a,x)=>a+toNumberPoin_(x.poin),0),pr=rew.reduce((a,x)=>a+toNumberPoin_(x.poin),0),bersih=Math.max(0,pp-pr);return{siswa:s,periode:getPeriodLabel_(period,params),absensi:abs,pelanggaran:pel,penghargaan:rew,poinPelanggaran:pp,poinPenghargaan:pr,poinBersih:bersih,keputusan:getKeputusanPoin_(bersih)};}
function toNumberPoin_(v){if(typeof v==='number')return isFinite(v)?v:0;const s=String(v==null?'':v).trim().replace(/\s/g,'').replace(',','.');const n=Number(s);return isFinite(n)?n:0;}
function dateRangeInclusive_(start,end){const a=start?parseDateInput_(start):null,b=end?parseDateInput_(end):null;if(a)a.setHours(0,0,0,0);if(b)b.setHours(23,59,59,999);return{a,b};}
function getPenghargaanSiswa_(nisn,start,end){const d=dbRead_(APP.SHEETS.PENGHARGAAN),range=dateRangeInclusive_(start,end),cn=dbFindColumn_(d.map,['NISN','NIS','Nomor Induk Siswa Nasional']),cd=dbFindColumn_(d.map,['Tanggal','Tanggal Penghargaan','Tgl']),cid=dbFindColumn_(d.map,['ID_Penghargaan','ID','ID Penghargaan']),cc=dbFindColumn_(d.map,['Kategori','Jenis']),cpres=dbFindColumn_(d.map,['Prestasi','Jenis Penghargaan','Penghargaan']),cp=dbFindColumn_(d.map,['Poin','Point']),cket=dbFindColumn_(d.map,['Keterangan','Catatan']);if(cn<0||cd<0||cp<0)return[];return d.rows.filter(r=>{const rv=String(r[cn]??'').trim(),dt=dbDate_(r[cd]);return rv===String(nisn).trim()&&dt&&(!range.a||dt>=range.a)&&(!range.b||dt<=range.b);}).map(r=>({id:cid>=0?r[cid]:'',tanggal:formatTanggal_(r[cd]),kategori:cc>=0?r[cc]:'',prestasi:cpres>=0?r[cpres]:'',poin:toNumberPoin_(r[cp]),keterangan:cket>=0?r[cket]:''}));}
function getRekapSheet_(period){return getSheet_(period==='bulanan'?APP.SHEETS.REKAP_BULANAN:period==='semester'?APP.SHEETS.REKAP_SEMESTER:APP.SHEETS.REKAP_TAHUNAN);}
function generateAndSaveRekap_(period,params){const data=buildRekap_(period,params),sh=getRekapSheet_(period),last=sh.getLastRow();if(last>1)sh.getRange(2,1,last-1,sh.getLastColumn()).clearContent();if(data.length){const vals=data.map(s=>period==='bulanan'?[params.month,params.year,s.nisn,s.nama,s.H,s.S,s.I,s.A,s.T,s.D,s.kehadiran,s.jmlPelanggaran,s.poinPelanggaran,s.poinPenghargaan,s.poinBersih,s.statusPembinaan]:period==='semester'?[params.tahunPelajaran||getTahunPelajaran_(),params.semester,s.nisn,s.nama,s.H,s.S,s.I,s.A,s.T,s.D,s.kehadiran,s.jmlPelanggaran,s.poinPelanggaran,s.poinPenghargaan,s.poinBersih,s.statusPembinaan]:[params.tahunPelajaran||getTahunPelajaran_(),s.nisn,s.nama,s.H,s.S,s.I,s.A,s.T,s.D,s.kehadiran,s.jmlPelanggaran,s.poinPelanggaran,s.poinPenghargaan,s.poinBersih,s.statusPembinaan]);sh.getRange(2,1,vals.length,vals[0].length).setValues(vals);}return data;}
function getRekapSnapshot_(period){const sh=getRekapSheet_(period),v=sh.getDataRange().getValues();if(v.length<2)return[];return v.slice(1).filter(r=>r.some(x=>x!==''&&x!=null)).map((r,i)=>period==='bulanan'?{row:i+2,bulan:r[0],tahun:r[1],nisn:String(r[2]),nama:r[3],H:+r[4]||0,S:+r[5]||0,I:+r[6]||0,A:+r[7]||0,T:+r[8]||0,D:+r[9]||0,kehadiran:+r[10]||0,jmlPelanggaran:+r[11]||0,poinPelanggaran:+r[12]||0,poinPenghargaan:+r[13]||0,poinBersih:+r[14]||0,statusPembinaan:r[15]||'NORMAL'}:period==='semester'?{row:i+2,tahunPelajaran:r[0],semester:r[1],nisn:String(r[2]),nama:r[3],H:+r[4]||0,S:+r[5]||0,I:+r[6]||0,A:+r[7]||0,T:+r[8]||0,D:+r[9]||0,kehadiran:+r[10]||0,jmlPelanggaran:+r[11]||0,poinPelanggaran:+r[12]||0,poinPenghargaan:+r[13]||0,poinBersih:+r[14]||0,statusPembinaan:r[15]||'NORMAL'}:{row:i+2,tahunPelajaran:r[0],nisn:String(r[1]),nama:r[2],H:+r[3]||0,S:+r[4]||0,I:+r[5]||0,A:+r[6]||0,T:+r[7]||0,D:+r[8]||0,kehadiran:+r[9]||0,jmlPelanggaran:+r[10]||0,poinPelanggaran:+r[11]||0,poinPenghargaan:+r[12]||0,poinBersih:+r[13]||0,statusPembinaan:r[14]||'NORMAL'});}
function updateRekapRow_(period,rowNumber,values){const sh=getRekapSheet_(period),r=Number(rowNumber);if(r<2||r>sh.getLastRow())throw new Error('Baris rekap tidak valid.');const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0],old=sh.getRange(r,1,1,sh.getLastColumn()).getValues()[0],v=values||{};['Hadir','Sakit','Izin','Alpa','Terlambat','Dispensasi'].forEach(k=>{const c=h.indexOf(k);if(c>=0&&v[k]!==undefined){const n=Number(v[k]);if(!isFinite(n)||n<0)throw new Error(k+' harus berupa angka 0 atau lebih.');old[c]=Math.floor(n);}});const hc=h.indexOf('Hadir'),tc=h.indexOf('Terlambat'),totalCols=['Hadir','Sakit','Izin','Alpa','Terlambat','Dispensasi'].map(k=>h.indexOf(k)).filter(c=>c>=0),total=totalCols.reduce((a,c)=>a+(Number(old[c])||0),0),had=(hc>=0?Number(old[hc])||0:0)+(tc>=0?Number(old[tc])||0:0),kc=h.indexOf('Kehadiran_%');if(kc>=0)old[kc]=total?Number((had/total*100).toFixed(2)):0;sh.getRange(r,1,1,old.length).setValues([old]);clearAppCache_();logActivity_('EDIT REKAP',period+' baris '+r);return getRekapSnapshot_(period).find(x=>x.row===r)||old;}
function deleteRekapRow_(period,rowNumber){const sh=getRekapSheet_(period),r=Number(rowNumber);if(r<2||r>sh.getLastRow())throw new Error('Baris rekap tidak valid.');sh.deleteRow(r);clearAppCache_();logActivity_('HAPUS REKAP',period+' baris '+r);return true;}

/** Dashboard dihitung satu kali baca, bukan getProfilPembinaan_ per siswa. */
function getDashboard_(){
  const cached=cacheGetJson_('DASHBOARD_CACHE');if(cached)return cached;
  const cfg=getConfigObject_(),students=getSiswaAktif_(),year=Number(String(cfg.Tahun_Pelajaran||new Date().getFullYear()).split('/')[0])||new Date().getFullYear(),sem=String(cfg.Semester||1),abs=getRekapAbsensi_('semester',year,null,sem,cfg.Kelas||''),b=getPeriodBounds_('semester',{year,semester:sem}),agg=aggregatePointPeriod_(b.start,b.end);let pel=0,rew=0,perlu=0;students.forEach(s=>{const a=agg[String(s.nisn).trim()]||{pel:0,rew:0};const bersih=Math.max(0,a.pel-a.rew);pel+=a.pel;rew+=a.rew;if(getKeputusanPoin_(bersih).status!=='NORMAL')perlu++;});const avg=abs.length?+(abs.reduce((a,b)=>a+b.kehadiran,0)/abs.length).toFixed(2):0;return cachePutJson_('DASHBOARD_CACHE',{totalSiswa:students.length,rataKehadiran:avg,totalPelanggaran:pel,totalPenghargaan:rew,perluPembinaan:perlu,config:cfg},30);}
function testRekap_(period,params){try{params=params||{};if(!['mingguan','bulanan','semester','tahunan'].includes(String(period)))throw new Error('Periode laporan tidak valid.');const ss=getSS_(),required=[APP.SHEETS.CONFIG,APP.SHEETS.SISWA,APP.SHEETS.ABSENSI,APP.SHEETS.PELANGGARAN,APP.SHEETS.PENGHARGAAN],missing=required.filter(n=>!ss.getSheetByName(n));if(missing.length)throw new Error('Sheet belum lengkap: '+missing.join(', ')+'. Jalankan setupDatabase_ terlebih dahulu.');const data=buildRekap_(period,params);return{success:true,period:period,periodLabel:getPeriodLabel_(period,params),jumlahBaris:data.length,sample:data.slice(0,3)};}catch(e){return{success:false,message:e&&e.message?e.message:String(e),stack:e&&e.stack?e.stack:''};}}
function getRekapForReport_(period,params){return buildRekap_(period,params||{});}
function diagnoseRekap_(period,params){params=params||{};const ss=getSS_(),result={period:String(period||''),params:params,sheets:{},siswa:0,absensi:0,absensiPeriode:0,rekap:0,headers:{}};[APP.SHEETS.SISWA,APP.SHEETS.ABSENSI,APP.SHEETS.PELANGGARAN,APP.SHEETS.PENGHARGAAN].forEach(n=>{const sh=ss.getSheetByName(n);result.sheets[n]=!!sh;if(sh){const v=sh.getDataRange().getValues();result.headers[n]=v.length?v[0]:[];if(n===APP.SHEETS.SISWA)result.siswa=Math.max(0,v.length-1);if(n===APP.SHEETS.ABSENSI){result.absensi=Math.max(0,v.length-1);const h=v.length?v[0].map(x=>String(x||'').trim().toLowerCase().replace(/[\s_-]+/g,'')):[],ct=['tanggal','tanggalabsensi','tgl'].map(x=>h.indexOf(x)).find(x=>x>=0);if(ct!==undefined)result.absensiPeriode=v.slice(1).filter(r=>{const d=parseDateInput_(r[ct]);if(!d)return false;const y=Number(params.year||new Date().getFullYear()),m=Number(params.month||1),sem=String(params.semester||'1'),yy=d.getFullYear(),mm=d.getMonth()+1;if(period==='bulanan')return yy===y&&mm===m;if(period==='semester')return sem==='2'?(yy===y+1&&mm<=6):(yy===y&&mm>=7&&mm<=12);return(yy===y&&mm>=7)||(yy===y+1&&mm<=6);}).length;}}});try{result.rekap=buildRekap_(period,params).length;}catch(e){result.error=e.message;}result.ok=true;return result;}
